AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  Nodejs4MysqlInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: nodjs-mysql-instance-profile
      Path: /
      Roles:
        - !Ref Ec2MysqlInstanceRole

  Ec2MysqlInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ec2-mysql-instance-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  NodejsInstanceRdsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref Ec2MysqlInstanceRole
      PolicyName: Ec2RdsPolicy

      PolicyDocument:
        Version: 2012-10-17
        Statement:
          [
            {
              "Effect": "Allow",
              "Action":
                [
                  "rds:*",
                  "application-autoscaling:DeleteScalingPolicy",
                  "application-autoscaling:DeregisterScalableTarget",
                  "application-autoscaling:DescribeScalableTargets",
                  "application-autoscaling:DescribeScalingActivities",
                  "application-autoscaling:DescribeScalingPolicies",
                  "application-autoscaling:PutScalingPolicy",
                  "application-autoscaling:RegisterScalableTarget",
                  "cloudwatch:DescribeAlarms",
                  "cloudwatch:GetMetricStatistics",
                  "cloudwatch:PutMetricAlarm",
                  "cloudwatch:DeleteAlarms",
                  "cloudwatch:ListMetrics",
                  "cloudwatch:GetMetricData",
                  "ec2:DescribeAccountAttributes",
                  "ec2:DescribeAvailabilityZones",
                  "ec2:DescribeCoipPools",
                  "ec2:DescribeInternetGateways",
                  "ec2:DescribeLocalGatewayRouteTablePermissions",
                  "ec2:DescribeLocalGatewayRouteTables",
                  "ec2:DescribeLocalGatewayRouteTableVpcAssociations",
                  "ec2:DescribeLocalGateways",
                  "ec2:DescribeSecurityGroups",
                  "ec2:DescribeSubnets",
                  "ec2:DescribeVpcAttribute",
                  "ec2:DescribeVpcs",
                  "ec2:GetCoipPoolUsage",
                  "sns:ListSubscriptions",
                  "sns:ListTopics",
                  "sns:Publish",
                  "logs:DescribeLogStreams",
                  "logs:GetLogEvents",
                  "outposts:GetOutpostInstanceTypes",
                  "devops-guru:GetResourceCollection",
                ],
              "Resource": "*",
            },
            {
              "Effect": "Allow",
              "Action": "pi:*",
              "Resource": "arn:aws:pi:*:*:metrics/rds/*",
            },
            {
              "Effect": "Allow",
              "Action": "iam:CreateServiceLinkedRole",
              "Resource": "*",
              "Condition":
                {
                  "StringLike":
                    {
                      "iam:AWSServiceName":
                        [
                          "rds.amazonaws.com",
                          "rds.application-autoscaling.amazonaws.com",
                        ],
                    },
                },
            },
            {
              "Action":
                [
                  "devops-guru:SearchInsights",
                  "devops-guru:ListAnomaliesForInsight",
                ],
              "Effect": "Allow",
              "Resource": "*",
              "Condition":
                {
                  "ForAllValues:StringEquals":
                    { "devops-guru:ServiceNames": ["RDS"] },
                  "Null": { "devops-guru:ServiceNames": "false" },
                },
            },
          ]

  NodejsInstanceS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Ec2MyqlS3Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::ltm893-mysql-bike-loads/*
              - arn:aws:s3:::ltm893-mysql-bike-loads
      Roles:
        - !Ref Ec2MysqlInstanceRole

  NodejsInstanceSsmPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Ec2MysqlSsmPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          [
            {
              "Effect": "Allow",
              "Action":
                [
                  "ssm:DescribeAssociation",
                  "ssm:GetDeployablePatchSnapshotForInstance",
                  "ssm:GetDocument",
                  "ssm:DescribeDocument",
                  "ssm:GetManifest",
                  "ssm:GetParameter",
                  "ssm:GetParameters",
                  "ssm:ListAssociations",
                  "ssm:ListInstanceAssociations",
                  "ssm:PutInventory",
                  "ssm:PutComplianceItems",
                  "ssm:PutConfigurePackageResult",
                  "ssm:UpdateAssociationStatus",
                  "ssm:UpdateInstanceAssociationStatus",
                  "ssm:UpdateInstanceInformation",
                ],
              "Resource": "*",
            },
            {
              "Effect": "Allow",
              "Action":
                [
                  "ssmmessages:CreateControlChannel",
                  "ssmmessages:CreateDataChannel",
                  "ssmmessages:OpenControlChannel",
                  "ssmmessages:OpenDataChannel",
                ],
              "Resource": "*",
            },
            {
              "Effect": "Allow",
              "Action":
                [
                  "ec2messages:AcknowledgeMessage",
                  "ec2messages:DeleteMessage",
                  "ec2messages:FailMessage",
                  "ec2messages:GetEndpoint",
                  "ec2messages:GetMessages",
                  "ec2messages:SendReply",
                ],
              "Resource": "*",
            },
          ]
      Roles:
        - !Ref Ec2MysqlInstanceRole

  EC2Nodejs:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Bring up app server
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              jq: []
              telnet: []
              mariadb: []
              npm: []
              node: []
          files:
            
            "/home/ec2-user/scripts/npminstalls":
              content: |
                #!/bin/bash
                set -eo pipefail
                cd /home/ec2-user/app/
                npm init -y 
                npm ci body-parser
                npm ci express
              mode: "000755"
              owner: ec2-user
              group: ec2-user

            "/home/ec2-user/scripts/simpleApp.service":
              content: |
                [Unit]
                Description=My Server
                After=network.target
                StartLimitIntervalSec=0

                [Service]
                Type=simple
                ExecStart=/usr/bin/python3 /home/ubuntu/my_server.py

                User=ubuntu

                Environment=ENV=production

                Restart=always
                RestartSec=1

                [Install]
                WantedBy=multi-user.target
              mode: "000755"
              owner: ec2-user
              group: ec2-user
                
                          

            "/home/ec2-user/app/bikeapp/server.js":
              content: |
                const express = require('express')
                const bodyParser = require('body-parser')

                const app = express()
                const port = 8080

                app.use(bodyParser.json())

                app.get('/', (req, res) => {
                    res.send('This is How we Move!')
                })

                app.get('/health', (req, res) => {
                    res.header({ "System-Health": true })
                    res.sendStatus(204)
                })

                const fibonacci = n => {
                    if (n <= 1) {
                        return n
                    }
                    return fibonacci(n - 1) + fibonacci(n - 2)
                }

                app.post('/fibonacci', (req, res) => {
                    const fibIndex = req.body.index
                    res.status(202).json({ index: fibIndex, result: "calculating..." })

                    console.log("Fibonacci number:", fibonacci(fibIndex))
                })

                app.listen(port, () => {
                    console.log(`App listening on port ${port}`)
                })       
              mode: "000755"
              owner: ec2-user
              group: ec2-user

            

          commands:
            01_npm_installs:
              command: '/bin/su -c "/home/ec2-user/scripts/npminstalls" - ec2-user'
        
            
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: !Ref Nodejs4MysqlInstanceProfile
      KeyName: Sys0
      ImageId: !Ref ImageId
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref InstanceSecurityGroup
          SubnetId: !ImportValue Ec2Subnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # Get the latest CloudFormation helper scripts
          yum install -y aws-cfn-bootstrap

          # Start cfn-init
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Nodejs --region ${AWS::Region}

          # cfn-init completed so signal success or not
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Nodejs --region ${AWS::Region}

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    #DependsOn: DBEC2SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !ImportValue TwoPubPrivVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0


Outputs: 
  EC2SecurityGroup:
    Description: Used by Lambda for access
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: Ec2IntanceSecurityGroupExport

  EC2Nodejs:
    Description: Used by API Gateway
    Value: !GetAtt  EC2Nodejs.PrivateDnsName
    Export:
        Name: Ec2InstancePrivateDnsExport
      
